// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxhTiI-vwL1y3ntwFaLCy9YnWHTcZ9bBk',
    appId: '1:218052201497:web:5610122ac85dde4e766e88',
    messagingSenderId: '218052201497',
    projectId: 'fleetmap-fe45f',
    authDomain: 'fleetmap-fe45f.firebaseapp.com',
    storageBucket: 'fleetmap-fe45f.firebasestorage.app',
    measurementId: 'G-59Z44NYPLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVLNLhmrau9rbXv-e9yKC8qftQrR1MJ9Q',
    appId: '1:218052201497:android:d8514153f6d0c294766e88',
    messagingSenderId: '218052201497',
    projectId: 'fleetmap-fe45f',
    storageBucket: 'fleetmap-fe45f.firebasestorage.app',
  );
}
